POST http://localhost:8080/test
Content-Type: application/json
sensitive-placeholder: (^_^)

{
  "email": "kiilin@kiilin.com",
  "idCard": "6222222222222222",
  "name": "云声",
  "phone": "18888888888",
  "username": "kiilin"
}
